[package]
name = "wolf-torrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencode = {git = "https://github.com/Rudranil-Sarkar/Bencode-parser-rust"}